---
name: Build and deploy a container image

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Checkout bookwyrm repo
      uses: actions/checkout@v3
      with:
        repository: bookwyrm-social/bookwyrm
        path: bookwyrm
        ref: production
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Apply the patch
      run: |
        pushd bookwyrm
        git config user.email "821688+tebriel@users.noreply.github.com"
        git config user.name "Chris Moultrie"
        git am ../patches/0001-Ship-the-app-and-ssl-config.patch
        git am ../patches/0002-Allow-static-hosting-in-Azure.patch
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: bookwyrm
        push: true
        tags: cmoultrie/bookwyrm:latest
